project_id = "coidecqncauwpjlkmbbk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://coidecqncauwpjlkmbbk.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[functions.ai-generate-title]
verify_jwt = false

[functions.ai-light-edit]  
verify_jwt = false

[functions.ai-expand-content]
verify_jwt = false

[functions.ai-condense-content]
verify_jwt = false

[functions.ai-outline]
verify_jwt = false

[edge_runtime]
policy = "per_worker"