import { UnifiedCommand } from '@/types/commands';

export function makeNewCommand(userId: string, sortOrder: number): UnifiedCommand {
  const now = new Date().toISOString();
  return {
    id: undefined as any, // Will be generated by database
    name: 'New Command',
    prompt: '',
    system_prompt: '',
    function_name: 'ai-light-edit',
    ai_model: 'gpt-5-mini-2025-08-07',
    max_tokens: 2000,
    temperature: 0.3,
    sort_order: sortOrder,
    user_id: userId,
    created_at: now,
    updated_at: now,
    icon: 'Sparkles',
    category: 'edit',
    description: '',
    estimated_time: '30s'
  };
}
