// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coidecqncauwpjlkmbbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaWRlY3FuY2F1d3BqbGttYmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzk2ODQsImV4cCI6MjA3MjIxNTY4NH0.46yshG9rT6Y4eM9dvBgAQiNVemDf2_2VJML52_A5-jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});